Algoritmo "calcular a área de um triangulo"

Var
// Seção de Declarações das variáveis 
 base, altura : real
 area : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("escreva aqui a base do triangulo: ")
leia(base)
escreva("escreva a altura do triangulo: ")
leia(altura)
     area <- (base * altura)/2
     escreva("a Area do Triangulo é : " , area)



Fimalgoritmo