Algoritmo "semnome"

Var
  primeiroNumero : inteiro
  segundoNumero : inteiro
  resultado : inteiro
Inicio
         escreva("Escreva o Primeiro Numero : ")
         leia(primeiroNumero)
         escreva("Escreva O Segundo Numero: ")
         leia(segundoNumero)
         
        resultado <-  primeiroNumero + segundoNumero
        escreval("o resultado da soma é :")
        escreva(resultado)


Fimalgoritmo