Algoritmo "verificar se os numeros sao iquais ou diferentes"

Var
// Seção de Declarações das variáveis 
        valor : inteiro
        valordois :inteiro
        soma : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
se valor == valordois Entao
 soma <- valor + valordois
 senao
 escreva("São Diferentes: " , valor,valordois)
 
fimse


Fimalgoritmo